language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm start > /dev/null &
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal $BROWSERSTACK_KEY localhost,8001,0 > /dev/null &
- sleep 10
after_success:
- cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
addons:
  code_climate:
    repo_token: 664b3bd95bef5ad8f8126fad7db731a0c9aaedbbc42223a1c3f668c550ab22a9
services:
- redis-server
sudo: false
env:
  global:
  - TRAVIS=true
  - PORT=3000
  - CHROME_EXTENSION_ID=none
  - OT_API_KEY=44935341
  - BROWSERSTACK_USERNAME=adamullman1
  - secure: AASeb3hNfOLvHvHBp7CZoBJ+Z5RMGqVIkvzmmdf2tCvkrdBj9pW9uZ3C4L0zV8FtECyR7aWKSOmIo80rvPxxPjnb5JnqJh47MkC2EHR+ofN3AMyD2br4u6xT4RmOe1sZELr0BJvmog7mSNJaS/trcOQ9BJX4+OMutfx53fM6HQu27cfGTG/A2w40nyFMrHg4DxmkYIIJH7a5RvNG11m/i0qTkRXq8TjKy9+m6O6yDWpXSbQQ9Wurw4H7J1FcxXdLZTM445YNrNxnSN/BNRo0Wo+8exJp1VEnCqoBrxV9PYtDTvwoy9QpAgVMZmofiGqPpZH03jUoDHEi8SEENGtpmiy/1AgKCLmZXacIElWfmWrODFIJv79ieDoCdItoN1acYSepGZjMGjgIv+zKsyfVPPIKu5Oezfj9pA764eoOc27AeA5iEQYJC4ktsNNO2slW0ICDFXN6JAVZ7pgu7MNnrqZnoJCB4Sxr0L7V9qJurApVueDT3DVtAbw/ktTK09o2TytGnvwbTmWuZzRjUF4laK71UUhkpRTg/5ZYSrHtHw4sXTjHK0XcJucKB46W91tXOGuSk96rcvks9vCf2O00xy4KElKgCFNXcjNEhIT3PLuxHMHn/42pjIVrALjbCfWXc1KaVvCHeyrgZmaaOesTmsPeH86rkKktGT2myeGeues=
  - secure: pLQuYfs9QQnwnfpEpAN9Tp+MJMDtgc7P4sYI0/cIqZKmbSCLWbNRT+m9lDFlPIBtMZg19vrWD98AZnS6/XAmwJGatXlRHM2gbfdDU4k83DagfBgiJWIgOh5hj9YFZ0x0ywNW7EFfSjChJDPj11ZVd5En3vrO5JorHxx1SgNco5OiJLkoynJvTcfS1D6oAc2blfGRLvUy9xysThnBGErB58T8RU6jpnrxsb0xqw2qKP6MGJpIhFf3qVV+oGcMBn8hJ4KqUkZbsGHTVNYqS47P+8IAgcZAAIcS+8eMDz+CH2kxhdBiG9e0lmuwx2huEgbJsqCh5+tWNS+btpgeWVG/mgy4EbZ0tipsqxnNX6wg9tIpHb9RfxSM76UPLfi5cteDatBli+gWzt/2pFGhezpHNIcxvpWo9Q2h40+At4fSLGtgqz5DDHelK+SwJJ1W4bUXTOhL4mKmNXO2uy1rDGOCSuFV+x6eofImoueF7Xt/csGrvcvK3H5mQZwOndFMpUvzrAOFdB7MlRGYokiB4B7JbQeNKq9mH9kAc0HTNjTSN2wLwo7KmnLQ/dzBzVICYsI4h9PgOwqkRnOCdR6G0pCCWNjP6ICsb/OaaNEl1b6OP1eAVpckwjxZn2Mf58bfeR++BtzOE/RJ+35ZLdiMVZ2bre2v05aEQGH8M2mLOe9UONE=
