language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm start > /dev/null &
- wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal $BROWSERSTACK_KEY localhost,8001,0 > /dev/null &
- sleep 10
after_success:
- cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
addons:
  code_climate:
    repo_token: 664b3bd95bef5ad8f8126fad7db731a0c9aaedbbc42223a1c3f668c550ab22a9
services:
- redis-server
sudo: false
env:
  global:
  - TRAVIS=true
  - PORT=3000
  - CHROME_EXTENSION_ID=none
  - OT_API_KEY=44935341
  - BROWSERSTACK_USERNAME=adamullman1
  - secure: kmTlYzWLrYsDZEdf58rZt1QVDEccfCRrD2mv074iNbDTQ90ceEaoWkkbsSOLBDA2gTSoYTOVqhiT3eoYz9CQfJZYxQOAE0OA+CfBnXyOzX/zMsQMHTEzVOjm34YM6B6cLaYF9lxPUvcHZhrNocBcM6zTRyIN0zSdi/DIo+v6GlU=
  - secure: TPwht7UzmCeV1lZdEPjdFNyGdDWT0yms92K+f+DJ5kD7WEt5ElS/cLyPId07VPnzIFbZ3Bu9k3vzFHFQ9ZEu0kruSgP49LT3oE3GuQfubeCtm08or/umGl8ma7/Mlpu4UXp78vU4688MpZpxW8nh64bMWmabZrltecjdIYFNxx8=
