language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm start &
after_success:
- cat coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
addons:
  code_climate:
    repo_token: 664b3bd95bef5ad8f8126fad7db731a0c9aaedbbc42223a1c3f668c550ab22a9
services:
- redis-server
env:
  global:
  - TRAVIS=true
  - PORT=5000
  - CHROME_EXTENSION_ID=none
  - OT_API_KEY=1974561
  - BROWSERSTACK_USERNAME=adamullman1
  - secure: R4BgZEwGLSaYExwCsSQMBDsbxIVowT/6W2GhEQ+buxPjKMu6Kwm4ddpsyoo2BPbkVRjeK5vCodS2e0VpXdSDQM11XzMbGnRdzIh6LF+yC011HfALQ8e/WN1yOvlK2wjIFNO3k8kp2Sw97cnib6A9JC8hANsElAZsBqDFZvDDx8A=
  - secure: Mkz+IPfvDv1QOt2HyBFrEXrVV67jAyBf6Xjk99K3dJceQDWxZndMZ0GbyxLymTYhH4ADANhMqb2wJgM+6PfGSHTKQ9FMqcUas9+RKy26S1SzWkQe6R0+SQw3NU4jV651Q3gQN5gu6sSoYpLQU9s+Jw0Khki8LFsPOiT/Qn/lwmM=
